import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { MyContextProvider } from "./Context/MyContext";
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const getpoppins = Poppins({
  variable: "--font-poppins",
  weight:["400","500","600","700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${getpoppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <MyContextProvider>
          <Navbar/>
          {children}
          <Footer/>
        </MyContextProvider>
        
        </body>
    </html>
  );
}
